version: '3.7'
services:
  web:
    image: rathaheang/httpd-php:7.4
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - .:/var/www/html
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php.ini:/etc/php7.4/apache2/php.ini
    ports:
      - 80:80
    networks:
      - wpherosite


  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wphero
    volumes:
      - db-data:/var/lib/mysql
      - .:/var/www/html
    networks:
      - wpherosite


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpherosite


networks:
  wpherosite:

volumes:
  db-data:
